name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configura Python para backend
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          cd react-flask-app/backend
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run backend tests
        run: |
          cd react-flask-app/backend
          python -m unittest discover || echo "No tests found"

      # 3️⃣ Configura Node.js para frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd react-flask-app/frontend
          npm install

      - name: Build frontend
        run: |
          cd react-flask-app/frontend
          npm run build
